import argparse
import json
import glob
import os
import re
import matplotlib.pyplot as plt
from pathlib import Path

def parse_checkpoint_step(path):
    # Extract number from "checkpoint-123"
    match = re.search(r"checkpoint-(\d+)", path)
    if match:
        return int(match.group(1))
    return -1

def get_accuracy_from_file(file_path, split_filter=None):
    total = 0
    correct = 0
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            for line in f:
                try:
                    data = json.loads(line)
                    
                    # Check split filter
                    if split_filter and split_filter != "all":
                        # The split info is in original_example -> dataset_split
                        # If not present, we assume it matches or ignore? 
                        # Safe to ignore if we want strict filtering.
                        ex_split = data.get("original_example", {}).get("dataset_split", "unknown")
                        if ex_split != split_filter:
                            continue

                    if "is_correct" in data:
                        total += 1
                        if data["is_correct"]:
                            correct += 1
                except json.JSONDecodeError:
                    continue
    except Exception as e:
        print(f"Error reading {file_path}: {e}")
        return 0.0

    if total == 0:
        return 0.0
    return correct / total

def main():
    parser = argparse.ArgumentParser(description="Plot accuracy vs checkpoint step")
    parser.add_argument("--results_dir", type=str, required=True, help="Base directory containing checkpoint outputs")
    parser.add_argument("--output_plot", type=str, default="checkpoint_metrics.png", help="Path to save the plot image")
    parser.add_argument("--domain", type=str, default="code", help="Domain filter (part of the timestamped folder name)")
    parser.add_argument("--split", type=str, default="test", help="Split filter (used to filter result folders AND data rows)")
    args = parser.parse_args()

    base_dir = Path(args.results_dir)
    checkpoint_dirs = glob.glob(str(base_dir / "checkpoint-*"))
    
    data_points = []

    print(f"Found {len(checkpoint_dirs)} checkpoint directories in {base_dir}")

    for cp_dir in checkpoint_dirs:
        step = parse_checkpoint_step(cp_dir)
        if step == -1:
            continue
            
        # Search for folders. We support:
        # 1. New deterministic structure: base/checkpoint-N/code_all/eval_results.jsonl
        # 2. Old timestamped structure: base/checkpoint-N/code_all_TIMESTAMP/eval_results.jsonl
        
        candidates = []
        
        # Check for non-timestamped folders first (preferred as they are "clean")
        # Direct matches
        for pat in [f"{args.domain}_all", f"{args.domain}_{args.split}"]:
            path = Path(cp_dir) / pat / "eval_results.jsonl"
            if path.exists():
                candidates.append(path)
        
        # Check for timestamped folders
        for pat in [f"{args.domain}_all_*", f"{args.domain}_{args.split}_*"]:
            folders = glob.glob(str(Path(cp_dir) / pat))
            folders.sort() # Latest timestamp last
            for folder in folders:
                 path = Path(folder) / "eval_results.jsonl"
                 if path.exists():
                     candidates.append(path)

        if not candidates:
            continue
            
        # If multiple exist, which one to pick?
        # Usually we want the *latest* one.
        # But if we have a mix of timestamped and non-timestamped, it's tricky.
        # Let's assume the non-timestamped one (generated by our new resume script) is the "canonical" one if it exists.
        # If not, take the latest timestamped one.
        
        # Wait, the shell script puts it in .../checkpoint-N/code_all/
        # But candidates contains full paths to jsonl files.
        # Let's pick the last one found? No, that's brittle.
        # Let's prioritize the deterministic one.
        
        chosen_file = None
        # Check specific priority paths
        p1 = Path(cp_dir) / f"{args.domain}_all" / "eval_results.jsonl"
        p2 = Path(cp_dir) / f"{args.domain}_{args.split}" / "eval_results.jsonl"
        
        if p1.exists():
            chosen_file = p1
        elif p2.exists():
            chosen_file = p2
        else:
            # Fallback to timestamped, picking the lexicographically last folder (latest date)
            valid_ts_files = []
            for c in candidates:
                # Filter out the non-timestamped ones we just checked
                if c != p1 and c != p2:
                    valid_ts_files.append(c)
            
            if valid_ts_files:
                # Sort by parent folder name (which contains timestamp)
                valid_ts_files.sort(key=lambda p: p.parent.name)
                chosen_file = valid_ts_files[-1]
                
        if not chosen_file:
            continue
            
        acc = get_accuracy_from_file(chosen_file, split_filter=args.split)
        print(f"Checkpoint {step}: Accuracy ({args.split}) = {acc:.2%} (from {chosen_file.parent.name})")
        data_points.append((step, acc))

    if not data_points:
        print("No valid data points found to plot.")
        return

    # Sort by step
    data_points.sort(key=lambda x: x[0])
    
    steps = [x[0] for x in data_points]
    accuracies = [x[1] for x in data_points]

    # Plotting
    plt.figure(figsize=(10, 6))
    plt.plot(steps, accuracies, marker='o', linestyle='-', color='b', label='Accuracy')
    
    plt.title(f'Model Accuracy vs Training Steps ({args.domain})')
    plt.xlabel('Checkpoint Step')
    plt.ylabel('Accuracy')
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.legend()
    
    # Save
    plt.savefig(args.output_plot)
    print(f"Plot saved to {args.output_plot}")

if __name__ == "__main__":
    main()
